apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  sourceHydrator:
    drySource:
      repoURL: https://github.com/leierx/homelab.git
      path: gitops/apps/argocd
      targetRevision: HEAD
      helm:
        valueFiles:
          - values.yaml
          - prod-values.yaml
    syncSource:
      targetBranch: env/prod
      path: gitops/hydrated/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true