certificate:
  dnsName: auth.invalid
authentik:
  authentik:
    disable_startup_analytics: true
    disable_update_check: true
  blueprints:
    configMaps:
      - authentik-default-locale
  server:
    envFrom:
      - secretRef:
          name: authentik-secrets
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: "2"
        memory: 2Gi
    route:
      main:
        enabled: true
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: ListenerSet
            name: authentik
            namespace: authentik
  worker:
    envFrom:
      - secretRef:
          name: authentik-secrets
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: "2"
        memory: 2Gi
  postgresql:
    enabled: true
    auth:
      existingSecret: authentik-postgresql
      secretKeys:
        adminPasswordKey: postgresql-postgres-password
    primary:
      persistence:
        storageClass: nfs
        size: 10Gi
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: "2"
          memory: 2Gi
