gateway:
  # ExternalIP/status address for the shared-gateway (per cluster).
  address: 192.168.100.10

gateway-helm:
  crds:
    enabled: false
gateway-crds-helm:
  crds:
    gatewayAPI:
      enabled: true
      channel: standard
    envoyGateway:
      enabled: true
