apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 48h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: authentik-secrets
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
        AUTHENTIK_POSTGRESQL__NAME: authentik
        AUTHENTIK_POSTGRESQL__USER: authentik
        AUTHENTIK_POSTGRESQL__PORT: "5432"
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: authentik/secret_key
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: authentik/postgresql-password
    - secretKey: AUTHENTIK_BOOTSTRAP_PASSWORD
      remoteRef:
        key: authentik/bootstrap-password
    - secretKey: AUTHENTIK_BOOTSTRAP_TOKEN
      remoteRef:
        key: authentik/bootstrap-token
    - secretKey: AUTHENTIK_BOOTSTRAP_EMAIL
      remoteRef:
        key: authentik/bootstrap-email
    - secretKey: AUTHENTIK_BOOTSTRAP_USERNAME
      remoteRef:
        key: authentik/bootstrap-username
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-postgresql
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 48h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: authentik-postgresql
  data:
    - secretKey: password
      remoteRef:
        key: authentik/postgresql-password
    - secretKey: postgresql-postgres-password
      remoteRef:
        key: authentik/postgresql-superuser-password
