apiVersion: promoter.argoproj.io/v1alpha1
kind: PromotionStrategy
metadata:
  name: homelab
  namespace: promoter-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  gitRepositoryRef:
    name: homelab
  environments:
    - branch: env/test
      autoMerge: true
    - branch: env/prod
      autoMerge: false