apiVersion: promoter.argoproj.io/v1alpha1
kind: ScmProvider
metadata:
  name: homelab
  namespace: promoter-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretRef:
    name: promoter-github-app
  github:
    appID: 4715868