apiVersion: promoter.argoproj.io/v1alpha1
kind: GitRepository
metadata:
  name: homelab
  namespace: promoter-system
spec:
  github:
    name: homelab
    owner: leierx
  scmProviderRef:
    name: homelab
