apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: authentik
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    acme.cert-manager.io/http01-parentreffallback: "true"
    argocd.argoproj.io/sync-wave: "-1"
spec:
  parentRef:
    name: shared-gateway
    namespace: gateway
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: {{ .Values.certificate.dnsName | quote }}
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: authentik-tls

