authentik:
  authentik:
    web:
      base_url: https://auth.test.skinke.net
  server:
    route:
      main:
        hostnames:
          - auth.test.skinke.net
certificate:
  dnsName: auth.test.skinke.net
