apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: shared-gateway-proxy
  namespace: gateway
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: NodePort
        externalTrafficPolicy: Cluster
        patch:
          type: StrategicMerge
          value:
            spec:
              ports:
                - name: http-80
                  port: 80
                  nodePort: 30080
                - name: https-443
                  port: 443
                  nodePort: 30443

