argo-cd:
  commitServer:
    enabled: true
  crds:
    install: true
  server:
    extraArgs:
      - --insecure
  applicationSet:
    extraArgs:
      - --policy=create-update
      - --enable-progressive-syncs
  configs:
    params:
      "hydrator.enabled": "true"
    cm:
      commit.author.name: "Hydrator Bot"
      commit.author.email: "argocd@homelab"