apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: authentik
  namespace: {{ .Release.Namespace }}
spec:
  parentRef:
    name: shared-gateway
    namespace: gateway
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: {{ .Values.certificate.dnsName | quote }}
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: authentik-tls

