apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-mgmt
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/leierx/homelab.git
        revision: HEAD
        files:
          - path: gitops/apps/*/app.yaml
        values:
          cluster: mgmt
          enabled: '{{ has "mgmt" .clusters }}'
      selector:
        matchExpressions:
          - key: values.enabled
            operator: In
            values: ["true"]
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: homelab.io/sync-wave
              operator: In
              values: ['w-1']
        - matchExpressions:
            - key: homelab.io/sync-wave
              operator: In
              values: ['w0']
  template:
    metadata:
      name: '{{ if eq (len .clusters) 1 }}{{ .name }}{{ else }}{{ .values.cluster }}-{{ .name }}{{ end }}'
      labels:
        homelab.io/sync-wave: '{{ printf "w%v" (.wave | default 0) }}'
    spec:
      project: default
      sourceHydrator:
        drySource:
          repoURL: https://github.com/leierx/homelab.git
          path: 'gitops/apps/{{.name}}'
          targetRevision: HEAD
          helm:
            valueFiles:
              - values.yaml
              - '{{.values.cluster}}-values.yaml'
            ignoreMissingValueFiles: true
        syncSource:
          targetBranch: 'env/{{.values.cluster}}'
          path: 'hydrated/{{.values.cluster}}/{{.name}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - Prune=true